#!/usr/bin/env bash

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
tmp_dir="$(mktemp -d)"
trap 'rm -rf "$tmp_dir"' EXIT

mkdir -p "$tmp_dir/src"

cat >"$tmp_dir/Cargo.toml" <<'EOF'
[package]
name = "sapient-test-harness-rules-generator"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
regex = "1"
EOF

cat >"$tmp_dir/src/main.rs" <<'RUST_EOF'
//! Extracts the conformance rule catalog directly from
//! `crates/sapient-conformance-core/src/validation/*.rs` and writes
//! `RULES.md`. Not part of the shipped crate -- run via
//! `scripts/generate-rules.sh`, mirroring `sapient-rs`'s own
//! `regenerate-*-bindings.sh` convention of a throwaway codegen program
//! rather than a permanent dependency of the library.
//!
//! # How extraction works
//!
//! Every rule ID in `validation::*` is a `snake_case.dotted.like.this`
//! string literal (see `src/finding.rs`'s naming convention), which is a
//! visibly different shape from the human-readable message strings next
//! to it (those have spaces, capitals, punctuation). That difference is
//! reliable enough to extract mechanically:
//!
//! 1. Strip each file's `#[cfg(test)]` module (test-only rule IDs, e.g.
//!    `common.rs`'s `"test.*"` placeholders, aren't real rules).
//! 2. Find every string literal shaped like a rule ID.
//! 3. One whose last `.segment` is `missing`/`invalid`/`malformed`/`empty`
//!    is a fully-resolved rule ID -- pair it with the next prose-shaped
//!    string literal that follows it (best-effort; the two are adjacent
//!    call arguments in every current call site).
//! 4. Anything else (e.g. `"alert.location"`) is a *prefix* passed to one
//!    of `common.rs`'s composite validators (`validate_location`,
//!    `validate_associated_file`, ...), which appends a fixed suffix
//!    internally to build the real rule IDs at runtime -- those are
//!    listed separately with the suffixes they combine with.

use std::{
    collections::BTreeMap,
    fmt::Write as _,
    fs,
    path::PathBuf,
};

use regex::Regex;

/// Files in the order they should appear in the generated document.
const FILE_ORDER: &[&str] = &[
    "sapient_message.rs",
    "registration.rs",
    "registration_ack.rs",
    "status_report.rs",
    "detection_report.rs",
    "task.rs",
    "task_ack.rs",
    "alert.rs",
    "alert_ack.rs",
    "error.rs",
    "common.rs",
];

/// Composite validators (in `common.rs`, reused across files, or local to
/// one file) that take a caller-supplied `rule_id_prefix` and append one
/// of these fixed suffixes internally. Kept as a small hand-maintained
/// table since these functions are few and stable -- see the named
/// source file for ground truth.
const PREFIX_SUFFIXES: &[(&str, &[&str])] = &[
    (
        "common.rs::validate_location",
        &[".x.missing", ".y.missing", ".coordinate_system.invalid", ".datum.missing"],
    ),
    (
        "common.rs::validate_range_bearing",
        &[".coordinate_system.invalid", ".datum.missing"],
    ),
    (
        "common.rs::validate_range_bearing_cone",
        &[".coordinate_system.invalid", ".datum.missing"],
    ),
    (
        "common.rs::validate_location_or_range_bearing",
        &[".missing", "(delegates to validate_range_bearing_cone / validate_location_list)"],
    ),
    (
        "common.rs::validate_location_list",
        &[".locations.empty", "(delegates to validate_location with \"{prefix}.locations\")"],
    ),
    (
        "common.rs::validate_associated_detection",
        &[".node_id.invalid", ".object_id.invalid"],
    ),
    (
        "common.rs::validate_associated_file",
        &[".type.missing", ".url.missing"],
    ),
    (
        "task.rs::validate_parameter (local, not common.rs)",
        &[".name.missing", ".operator.missing", ".value.missing"],
    ),
    (
        "detection_report.rs::validate_sub_class (local, not common.rs)",
        &[".type.missing", ".level.missing"],
    ),
    (
        "detection_report.rs::validate_track_object_info (local, not common.rs)",
        &[".type.missing", ".value.missing"],
    ),
];

struct Rule {
    id: String,
    message: Option<String>,
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let repo_root = PathBuf::from(std::env::args().nth(1).ok_or("missing repo root")?);
    let validation_dir =
        repo_root.join("crates/sapient-conformance-core/src/validation");

    let rule_id_re = Regex::new(r#""([a-z][a-z0-9_]*(?:\.[a-z][a-z0-9_]*)+)""#)?;
    let violation_kinds = ["missing", "invalid", "malformed", "empty"];

    let mut out = String::new();
    writeln!(out, "# Conformance rule catalog")?;
    writeln!(out)?;
    writeln!(
        out,
        "Generated by `scripts/generate-rules.sh` from `crates/sapient-conformance-core/src/validation/*.rs`. \
         Do not hand-edit -- rerun the script instead."
    )?;
    writeln!(out)?;
    writeln!(
        out,
        "Every rule ID follows `<message_type>.<field>.<violation_kind>`, where \
         `violation_kind` is one of `missing` (a mandatory field is absent), `invalid` \
         (present but fails a format/range/enum check), `malformed` (present but \
         structurally broken -- mainly out-of-range timestamp nanos), or `empty` \
         (present but an empty collection/string where at least one entry is required). \
         See `src/finding.rs` for the full contract."
    )?;
    writeln!(out)?;

    for file_name in FILE_ORDER {
        let path = validation_dir.join(file_name);
        let content = fs::read_to_string(&path)
            .map_err(|err| format!("failed to read {}: {err}", path.display()))?;
        let production_code = strip_test_module(&content);

        let (mut resolved, mut prefixes) = (Vec::new(), Vec::new());
        let mut seen_resolved = BTreeMap::new();
        let mut seen_prefixes = Vec::new();

        for capture in rule_id_re.captures_iter(production_code) {
            let literal = capture.get(1).unwrap();
            let text = literal.as_str();
            let is_resolved = text
                .rsplit('.')
                .next()
                .map(|last| violation_kinds.contains(&last))
                .unwrap_or(false);

            if is_resolved {
                // Search from after the literal's closing quote, not after
                // the inner capture group (which ends *before* it) --
                // otherwise the leftover closing quote becomes the opening
                // quote of a bogus first "match".
                let search_from = capture.get(0).unwrap().end();
                let message = find_paired_message(production_code, search_from, &rule_id_re);
                seen_resolved.entry(text.to_string()).or_insert(message);
            } else if !seen_prefixes.contains(&text.to_string()) {
                seen_prefixes.push(text.to_string());
            }
        }

        for (id, message) in seen_resolved {
            resolved.push(Rule { id, message });
        }
        for prefix in seen_prefixes {
            prefixes.push(prefix);
        }

        if resolved.is_empty() && prefixes.is_empty() {
            continue;
        }

        writeln!(out, "## `{file_name}`")?;
        writeln!(out)?;

        if !resolved.is_empty() {
            writeln!(out, "| Rule ID | Message |")?;
            writeln!(out, "|---|---|")?;
            for rule in &resolved {
                let message = rule.message.as_deref().unwrap_or("*(see source)*");
                writeln!(out, "| `{}` | {} |", rule.id, message)?;
            }
            writeln!(out)?;
        }

        if !prefixes.is_empty() {
            writeln!(
                out,
                "Rule ID prefixes passed to `common.rs`'s composite validators (each \
                 combines with a fixed suffix at runtime to build the real rule IDs):"
            )?;
            writeln!(out)?;
            for prefix in &prefixes {
                writeln!(out, "- `{prefix}.*`")?;
            }
            writeln!(out)?;
        }
    }

    writeln!(out, "## Composite validator suffixes")?;
    writeln!(out)?;
    writeln!(
        out,
        "Each prefix above is combined with these suffixes by the named function \
         (in `common.rs` unless noted otherwise) to build the fully-resolved rule IDs \
         actually produced at runtime."
    )?;
    writeln!(out)?;
    for (function, suffixes) in PREFIX_SUFFIXES {
        writeln!(out, "- `{function}`: {}", suffixes.join(", "))?;
    }

    fs::write(repo_root.join("RULES.md"), out)?;

    Ok(())
}

/// Everything in `content` up to (not including) the file's `#[cfg(test)]`
/// module, so test-only placeholder rule IDs aren't picked up.
fn strip_test_module(content: &str) -> &str {
    match content.find("#[cfg(test)]") {
        Some(index) => &content[..index],
        None => content,
    }
}

/// Best-effort pairing: the next string literal after `rule_id`'s closing
/// quote that isn't itself rule-ID-shaped is treated as its message.
fn find_paired_message(content: &str, search_from: usize, rule_id_re: &Regex) -> Option<String> {
    const SEARCH_WINDOW: usize = 400;
    let window_end = (search_from + SEARCH_WINDOW).min(content.len());
    let window = &content[search_from..window_end];

    let string_re = Regex::new(r#""((?:[^"\\]|\\.)*)""#).ok()?;
    for capture in string_re.captures_iter(window) {
        let text = capture.get(1)?.as_str();
        if !rule_id_re.is_match(&format!("\"{text}\"")) {
            return Some(text.to_string());
        }
    }
    None
}
RUST_EOF

echo "Generating RULES.md..."
cargo run --quiet --manifest-path "$tmp_dir/Cargo.toml" -- "$repo_root"
echo "RULES.md generated at $repo_root/RULES.md"
